### ISSUE TITLE
🐛 AdminSet disappears when valkyrized

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/adventist_knapsack#755]
# Summary

This bug is affecting both Adventist and Pals. (HykuUp has not been investigated)

There are numerous issues when converting AdminSets to Valkryie objects. 
- the objects disappear from views as valid for selecting for a new work (both the app UI and Bulkrax importers)
- the objects disappeared from the dashboard index view
- the AdminSet edit view throws 500 errors

When the admin set migration is reversed, by deleting the Valkyrie table entry, it is still unusable until a creator is added via the UI.

(It is unknown whether any similar issues also affect collections.)

# Acceptance Criteria

- [ ] Admin sets can be edited and saved and will lazy migrate
- [ ] Admin set views work (index, show, edit)
- [ ] All valid admin sets are found via queries (AdminSet, AdminSetResource, and Hyrax::AdministrativeSet are all found, regardless of which is configured for current use). 

# Screenshots or Video

# TODO
- [ ] FIx is going into Hyku - we'll need to update submodules for
  - [ ] pals knapsack
  - [ ] hyku up knapsack
  - [ ] adventist
  - [ ] knapsack prime

# Notes

There are also issues with the facets on the dashboard views. The same facet will show multiple times, or in various ways. 
- [ ] Dashboard index facets appear to be duplicated due to Collection vs CollectionResourceResource or AdminSet, Admin Set, Hyrax::AdministrativeSet differences

![Screenshot 2024-08-19 at 11 58 59 AM](https://github.com/user-attachments/assets/a22f34b7-b592-4e90-98c5-074be4f9e5e9)

**⚠️ This blocks Adventist and Pals from deploying valkyrie to production ⚠️**

**Comment by ShanaLMoore** [comment]
Did GBH experience these issues?

**Comment by laritakr** [comment]
> Did GBH experience these issues?

I don't know. We probably need to test HykuUp, because it's likely that the tenants that existed pre-valkyrie may have issues too.

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ❌ NEEDS REWORK

cc @laritakr 

On [STAGING](https://demo.s2.adventistdigitallibrary.org/dashboard/my/collections?locale=en) I edited the default admint set. After clicking save, I can no longer see it in the collection index page. I've confirmed the latest sha was deployed. Am I missing something? 



![Image](https://github.com/user-attachments/assets/f6eefe44-410f-46f5-88b4-2226214e0088)



![Image](https://github.com/user-attachments/assets/e5a7cbc4-0720-46f5-9987-d5a023880ed2)

**Comment by laritakr** [comment]
@ShanaLMoore your after photo was "my collections" not "all collections. It is there. 

![Image](https://github.com/user-attachments/assets/6c494480-8a76-49f8-8ddd-a9ac994ba0e8)



![Image](https://github.com/user-attachments/assets/0e45455d-7e5f-4abd-a842-505dafbd2010)

**Comment by ShanaLMoore** [comment]
omg 🤦‍♀ Thanks 😬 you're correct. I was looking at the wrong tab. 🙃
